name: Test Action (push)

on: [push]

jobs:
  fcs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test FCS CLI IaC Scan
        uses: ./
        id: fcs
        with:
          falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
          falcon_region: ${{ vars.FALCON_CLOUD_REGION }}
          config: 'tests/config.json'
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

      - name: Upload SARIF report to GitHub Code scanning
        uses: github/codeql-action/upload-sarif@v2
        if: steps.fcs.outputs.exit-code != 0
        with:
          sarif_file: ./*-scan-results.sarif
